### ISSUE TITLE
multiple params ?

### ISSUE THREAD

**Issue by previousdeveloper** [developit/resource-router-middleware#4]

**Comment by developit** [comment]
@previousdeveloper - I assume you mean to load()?

**Comment by nikrich** [comment]
I have encountered he same.

If I, say have a route user/:id/address I am unable to access the id of the user from the address resource. This is happening in index() when loading a list.

**Comment by nikrich** [comment]
Tested the latest change and it works. Updated Readme and created pull request :)

Regards

**Comment by developit** [comment]
Awesome. @nikrich + @previousdeveloper is this fixed enough we can close?

**Comment by nikrich** [comment]
Yeah, working 100%. Go ahead and close
