### ISSUE TITLE
Load model async?

### ISSUE THREAD

**Issue by thijsw** [developit/resource-router-middleware#8]
Hello, thanks for this little gem. I'm having trouble getting the load function to work when the callback is called asynchronously.

Example (Project is a model from bookshelf.js)
```js
  // (...)

  load(req, id, callback) {
    Project
      .where('id', id)
      .fetch()
      .then(model => {
        callback(null, model);
      })
      .catch(Project.NotFoundError, (error) => {
        callback(error, null);
      });
  },

  // (...)
```

Does anybody know if this is supposed to work or is it a known limitation of the load method?

**Comment by developit** [comment]
Load's callback is designed for that use-case.  What's the issue you're seeing - getting an error?

Remember, the value will be set on `req` as whatever you specify for `id`:

```js
resource({
  id: 'project',
  load(req, id, callback) {
    Project
      .where('id', id)
      .fetch()
      .then(callback.bind(null,null), callback);
  },
  read(req, res) {
    req.project;    // the Project model from load
  }
});
```

**Comment by thijsw** [comment]
Thanks for your swift response! It was just an error on my side, I forgot to rename the `model` parameter in the `({ model, body }, res)` method signature of `read()` (it should have been `project` in my case). Those params get extracted from `req` of course. Thanks again!
